# Contents of the JSON file you downloaded

# URL of your Google Sheet
login_sheet_url = "https://docs.google.com/spreadsheets/d/120ZT_vHNgAPS1L2VshL-DDBJp5462yl3W_-9W9TKTrI/edit?gid=0#gid=0"

[gsheet_credentials]
type = "service_account"
project_id = "portfolio-tracker-480112"
private_key_id = "15f4ad246248042c530091b6788d7da31b7345fe"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDb0vNAs4YZd5OT
H00vfePr9GDU5HXsBvVICGznfbE1n0gUU4lh37PyNkHNnFR/KTxjGO1VSJTyd2SU
v/zeyhqMfPDiYcm8E2qffxWobtpdcoBktEjnE8Tyc47f8fA10o21K5+boMPE1eHA
DXOgLFbFYUR+k/RxWdTTIEhW9EZpTKZJ4IJ+CXlARpjuvSXRuUXNyPJMVP+1oB/F
xKqse/w20YbX9KTZBComzOC6kt+pAN+qFG2aSPL2jps3sXvdvHkVl/B08/+c6AXI
B5mpyH0RQR7/TRkIlbGzNvfUwAfEXvMFiLUuLCQCYt3+tjIG+MhCfqTHOPWA1bu9
5lIHwsfDAgMBAAECggEAS8Ep1T1I1FPyBnx+BATVXAYurI9C2CEZvEYzCZ+2Ry1q
EJ8tNA58m9b43Fuoft3+EoSPnZlSwzBD+EMlaL2rYojYFpvugqMKVobcNtxk4llI
R+wdR4z3jTonnaNpzZKPBUVQTribXqT6lE3Ob/93s7OugBSK49k6T7vLUjQCY9zD
yIQzakEeYH4AAUF6gNZjdoOg/WMXQpSqc4nBqw4N9W4RGutvQX0+YDUOFo4x1FA5
z03nodOJTNxxwqyqfacaqopUWRk/rxpJ+Z+H0qPnR2vjNkdRvRe1LIzKdNlS3GSX
R9zLjt/6MFxpoyY8y8OfirsSYELuiJQ/SXn5qdR0QQKBgQD0tG1U19mt5wfG8dQd
YN5xFwUTb44a7SVp47xR6gUD84A9J9XC2VO1/XsRnmlmjq+9l3iKknKaG3XVeVpQ
YmfzQtsf8EyWij0jwi2Ulu09DW1PybONg5cwqtsXEnsFOmECPzIHv7+cVJMdm37T
rFfkGyhfjgHDQJjW4h3MDsCcYwKBgQDl+ISCn0cUnGDJFkuMPXmEU9gKg12p+EHM
G8VAtYAscZBZd2T3ANnicgdHQO3tGVdsL5tjib7NjlnFeFqI0k7RUWrF+6/Ymtt5
mEsmIsMyvO/JyhTqGuTWswedI3sMBK0o9P4OVm7gJ+HXlXcvW/j7qImGn1cPqYT5
d/b2CEOVIQKBgGZ9f2FOurxsjERWGypm3SPuqVCXo6RBeS8dlE2Wv50FCswSeCSR
E8+gqEAb4jdzQcYdv/4CEn/bSoIrvpj2bmVjthVtdxaCNdNZS+/1Os4cZpFJgKuf
1t4qYXMLaX0qE2F2iITYWe+nOKro6rjLcVB303QaLUDTOHCf6i0CbMfTAoGALrSA
RP8QMpFn3q8WfM7nZQaaM9hmJ2TyCAAD2ZaDB4Ow61qiOMAFgEXkUIZRS/v/k0s/
5cFN7PViKga9bFg6BazhYIAzQGyC8nkJmh8pQZ65nGPcR4davnfxrepMzS4N9Ol8
x3CqZ//xkBUc9ZNaR9H8zEiEJ/wns3q3v1QCVcECgYEAw6dlr16MRaGckuQwVepj
XoDzXusXYgd0vO+6NrBATBcYLb6TSmembfdDgjoDcG1gjkHNVVihf7QCDp/0756v
goahJuFZSW52oMZgwZbU0Ei1N6Cc7BDO+ttkau+HZElb3HLNbghROhozwiHi1dCl
ctOKY49OjqDEsIOXiE7G7B0=
-----END PRIVATE KEY-----
"""
client_email = "portfolio-login-tracker@portfolio-tracker-480112.iam.gserviceaccount.com"
client_id = "112346012434264910270"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40project.iam.gserviceaccount.com"
